spring:
  application:
    name: provider

  datasource:
    username: TEST
    password: test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: provider${server.port} #将status栏的 （类似 DESKTOP-2021RRP:client:8081 ） 换成 这个id
    prefer-ip-address: true  # 鼠标移到status栏，左下角默认是类似 DESKTOP-2021RRP:client:8081 ，改成IP地址显示