server:
  port: 8001

spring:
  application:
    name: provider

  datasource:
    username: TEST
    password: test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver