spring:
  application:
    name: provider
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

  datasource:
    username: C##TEST   #家里的话换成C##TEST   笔记本用TEST
    password: 123456    #家里的话换成C##TEST   笔记本用test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521/ORCL    #  家里用ORCL   笔记本用XE
    driver-class-name: oracle.jdbc.driver.OracleDriver




#  datasource:
#    username: C##TEST   #家里的话换成C##TEST   笔记本用TEST
#    password: 123456    #家里的话换成C##TEST   笔记本用test
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:oracle:thin:@localhost:1521/ORCL    #  家里用ORCL   笔记本用XE
#    driver-class-name: oracle.jdbc.driver.OracleDriver


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: provider${server.port} #将status栏的 （类似 DESKTOP-2021RRP:client:8081 ） 换成 这个id
    prefer-ip-address: true  # 鼠标移到status栏，左下角默认是类似 DESKTOP-2021RRP:client:8081 ，改成IP地址显示